Repository wagerr/wagerr, pull requests merged in 2018-10, with the labels that each got.

#79 Qt update betting timeout
  src/qt/placebetdialog.cpp
  src/qt/walletview.cpp
Labels: GUI

#80 Add checkpoint for block 320000
  src/chainparams.cpp
Labels: Validation

#83 [FIX] [#76] Change notification popup if-clause
  src/qt/bitcoingui.cpp
Labels: GUI, Patch

#84 Event listing on the QT showing Aug instead of Oct.
  src/qt/walletview.cpp
Labels: GUI
