Repository wagerr/wagerr, pull requests merged in 2018-12, with the labels that each got.

#99 Contrib: add gitian-build.py script
  contrib/gitian-build.py
Labels: Build system

#100 Update snapcraft
  snap/snapcraft.yaml
Labels: Build system

#95 Add warning in RPC Console about divulging private keys
  src/qt/rpcconsole.cpp
Labels: GUI

#77 Scripts and instructions for Wagerr Masternode setup
  contrib/wagerr-mn-setup/README.md
  contrib/wagerr-mn-setup/wagerr_install.sh
Labels: Scripts and tools

#91 Fixup to get arm32/64 GUI packages building again
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/packages/xextproto.mk
  depends/patches/qt/aarch32-qmake.conf
  depends/patches/qt/aarch64-qmake.conf
  depends/patches/xextproto/fix_aarch64_build.patch
Labels: Build system, GUI, Linux/Unix, Patch

#89 Event dialog on the QT showing Aug instead of Oct
  src/qt/placebetdialog.cpp
Labels: Patch

#101 Travis: add Cross-Mac Darwin 14 compilation
  .travis.yml
Labels: Build system
