Repository wagerr/wagerr, pull requests merged in 2018-09, with the labels that each got.

#70 Windows signing script
  contrib/gitian-descriptors/gitian-win.yml
  contrib/macdeploy/detached-sig-create.sh
  contrib/windeploy/detached-sig-create.sh
  contrib/windeploy/win-codesign.cert
Labels: Build system

#67 Disable buttons to accidentally burn coins
  src/qt/forms/placebetdialog.ui
  src/qt/placebetevent.cpp
Labels: GUI

#66 Add RPC call for spending zWGR with coin control
  src/rpc/client.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/rpcwallet.cpp
Labels: RPC/REST/ZMQ

#68 [Qt] Clean up Multisend Dialog UI
  src/qt/multisenddialog.cpp
  src/qt/multisenddialog.h
Labels: GUI, Refactoring

#69 Contrib: Replace developer keys with list of pgp fingerprints
  contrib/gitian-keys/README.md
  contrib/gitian-keys/keys.txt
  contrib/gitian-keys/wagerrtor.gpg
Labels: Docs

#64 Count masternode coins once instead of twice
  src/wallet.cpp
Labels: Wallet

#65 Add extended balance RPC call
  src/rpc/client.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/rpcwallet.cpp
Labels: RPC/REST/ZMQ

#72 Updated checkpoint handling to enable zWGRv1 spending
  src/accumulatorcheckpoints.json.h
  src/accumulators.cpp
  src/chainparams.cpp
  src/rpc/blockchain.cpp
  src/wallet.cpp
Labels: Patch

#74 Qt: Add notice about betting fee on betting page
  src/qt/forms/placebetdialog.ui
Labels: GUI
