Repository wagerr/wagerr, pull requests merged in 2019-11, with the labels that each got.

#179 Implemented getbet RPC API for light clients
  src/rpc/client.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/wallet/rpcwallet.cpp
Labels: RPC/REST/ZMQ

#180 [FIX] Update handling of spreads and totals
  src/betting/bet.cpp
Labels: Bug

#181 Update vector, string and runtime_error in getbet RPC call
  src/wallet/rpcwallet.cpp
Labels: Patch

#182 Release notes for 3.1.0 and set protocol/stake modifier versions/heights
  doc/release-notes/release-notes-3.1.0.md
  src/chainparams.cpp
  src/version.h
Labels: Consensus, Docs

#186 Update snapcraft.yaml to use v3.1.0 when building
  snap/snapcraft.yaml
Labels: Build system, Linux/Unix, Scripts and tools

#191 Update to build s390x and powerpc64le in gitian build
  contrib/gitian-descriptors/gitian-linux.yml
  depends/hosts/linux.mk
  depends/packages/qt.mk
  src/compat/glibc_compat.cpp
Labels: Build system, Feature, Linux/Unix, Patch
