Repository wagerr/wagerr, pull requests merged in 2019-08, with the labels that each got.

#137 Installation on Raspberry PI
  doc/Wagerr Raspberry Pi Install.md
  doc/img/appmenu.png
  doc/img/wagerr-qt.png
Labels: Docs, Linux/Unix, Scripts and tools, Wallet

#158 Add in port for regtest at 55007
  src/chainparamsbase.cpp
Labels: Build system, Patch, RPC/REST/ZMQ, Scripts and tools, Tests, Validation

#159 Add in Oracle addresses for regtest
  src/chainparams.cpp
Labels: Patch, RPC/REST/ZMQ, Scripts and tools, Tests

#160 3.0.1 backports
  src/chainparams.cpp
  src/chainparams.h
  src/chainparamsbase.cpp
  src/main.cpp
  src/qt/res/images/about.png
  src/qt/res/images/splash.png
  src/qt/res/images/wagerr_logo_horizontal.png
Labels: Backport

#168 Remove jobs causing travis to fail
  test/functional/test_runner.py
Labels: Bug, Build system, Linux/Unix, Patch, Scripts and tools, Tests

#172 Patches from pivx commit 2eacdb7f46673de758dd273a53effe2
  src/chainparams.cpp
  src/chainparams.h
  src/kernel.cpp
  src/main.cpp
  src/main.h
  src/wallet/wallet.cpp
Labels: Bug, Linux/Unix, Patch, Tests, Upstream
