Repository wagerr/wagerr, pull requests merged in 2020-12, with the labels that each got.

#233 Update QT Sidebar Colors
  src/qt/res/css/default.css
Labels: GUI

#231 Update snap build version to 4.0.99
  snap/snapcraft.yaml
Labels: Build system, Linux/Unix, Scripts and tools

#236 Update timestamps in tests to 1902871341
  src/test/rpc_tests.cpp
Labels: Build system, Linux/Unix, Scripts and tools, Tests
